import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Providers } from './providers';
import clsx from 'clsx';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'NextJS React Training',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, 'bg-zinc-900')}>
        <Providers>
          <main className="min-h-screen flex flex-col items-center justify-center w-full bg-linear-to-tr from-zerf-contrast via-zerf/90 to-zerf text-white gap-4">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
