import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Providers } from './providers';
import clsx from 'clsx';
import FilterButton from '@/components/Common/FilterButton';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'NextJS React Training',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-white min-h-screen">
        <header className="w-full py-8 flex justify-center">
          <h1 className="text-3xl sm:text-5xl md:text-6xl font-light text-black">StyleSage</h1>
        </header>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
